COERCION_PROTOTYPES = {
    "CREDENTIAL_PHISHING": [
        "Your login session has expired. Sign in again to continue.",
        "Please verify your username and password to restore access.",
        "We detected an issue with your login credentials. Re-enter your password.",
        "Your account requires authentication. Sign in to verify your identity.",
        "Click below and log in to confirm that you are the account owner.",
        "Your password needs to be verified to prevent your account from being disabled.",
        "Sign in immediately to keep your account active.",
        "We were unable to verify your login information. Please authenticate again.",
        "Your access has been temporarily restricted. Log in to restore it.",
        "Confirm your account by entering your username and password.",
        "A security check requires you to sign in again.",
        "Please log in through the secure portal to complete verification.",
        "Your authentication session requires confirmation. Enter your credentials.",
        "Re-enter your login details to avoid losing access.",
        "We need you to confirm your password for security purposes.",
        "Sign in now to verify that this account belongs to you.",
        "Your account cannot be accessed until you complete the login verification.",
        "Please provide your login credentials to continue using the service.",
        "Authentication is required to maintain uninterrupted access.",
        "Log in through the link below to complete the required security check.",
        "Your username and password must be confirmed before access can continue.",
        "Please sign in to validate your account credentials.",
        "A verification request is pending. Log in to complete the process.",
        "Enter your account password to confirm your access.",
        "Your login information needs to be updated through the verification page.",
        "Sign in using your existing credentials to complete authentication.",
        "We require immediate confirmation of your login details.",
        "Please authenticate your account through the secure sign-in page.",
        "Your access requires credential verification. Log in now.",
        "To continue, confirm your identity by signing into your account.",
        "We need to verify your login details before granting access.",
        "Your credentials could not be validated. Please sign in again.",
        "Complete the authentication process by entering your username and password.",
        "A login verification is required to confirm continued access to your account.",
        "Follow the link and sign in to complete the account authentication process."
    ],
    "ACCOUNT_TAKEOVER" : [
        "We detected an unauthorized change to your account recovery settings and need you to review recent activity.",
        "Your account appears to have been accessed from a new device and security controls have been triggered.",
        "Someone has taken control of your profile and changed important account settings.",
        "We noticed your registered email address was recently replaced without your authorization.",
        "Your account recovery phone number has been changed by an unknown user.",
        "Multiple unauthorized actions were performed from your account after a suspicious login.",
        "Your account ownership may have been compromised and administrative control is being transferred.",
        "An unknown user has added a new administrator to your account.",
        "Your account session was taken over from another location and changes are currently being made.",
        "We detected that someone is using your account to communicate with your contacts without permission.",
        "A suspicious user has gained access to your account and is attempting to lock you out.",
        "Your account password was changed recently and we believe the change was not made by you.",
        "An unauthorized party has modified your account permissions and security settings.",
        "Your account is currently being controlled from an unfamiliar device.",
        "Someone has linked their own recovery information to your account.",
        "We detected a takeover attempt involving changes to your account ownership details.",
        "Your account has been accessed by another person who is attempting to retain permanent control.",
        "An unfamiliar user has enabled additional authentication methods on your account.",
        "Your profile information and account settings were altered following suspicious account access.",
        "We believe an unauthorized person is impersonating you through your compromised account.",
        "Your account access privileges have been modified by someone other than the registered owner.",
        "A new trusted device was added to your account without your approval.",
        "Your account has been locked after another user attempted to establish control over it.",
        "We detected suspicious activity indicating that your account may have been hijacked.",
        "An unknown party is attempting to prevent you from regaining control of your account."
    ],
    "IDENTITY_INFORMATION_THEFT" : [
        "We need you to provide your full name, date of birth, address, and government identification number to complete this verification.",
        "Your personal identity information must be updated immediately by submitting a copy of your identification document.",
        "Send us a scanned copy of your passport and proof of address so we can confirm your identity.",
        "Please provide your Social Security number and date of birth to complete the required identity registration.",
        "We require a clear photograph of your government-issued ID along with your residential address for our records.",
        "Your identity profile is incomplete; submit your full legal name, date of birth, and identification number immediately.",
        "Reply with a copy of your Aadhaar card and PAN card so your personal records can be verified.",
        "To process your identity verification, send your passport number, home address, and date of birth.",
        "Please upload both sides of your driver's license along with a recent utility bill containing your address.",
        "We need your complete personal details, including your date of birth and national identification number, for verification.",
        "Submit a photograph of your identity card and proof of residence to avoid delays in processing your personal profile.",
        "Your government identification details need to be reconfirmed; please send the requested documents.",
        "Provide your full identity information and a copy of an official photo ID to complete this mandatory registration.",
        "Our records require verification of your personal identity, including your legal name, address, and identification document.",
        "Please send a copy of your passport along with your date of birth and current residential address.",
        "To validate your identity, we require your national ID number and a photograph of the physical identification card.",
        "Your personal information needs to be verified against official records; submit your identity documents now.",
        "Send us your full legal name, date of birth, home address, and a copy of your government-issued identification.",
        "We are conducting an identity records update and require you to provide your personal identification details.",
        "Please complete the identity form by entering your full name, birth date, residential address, and government ID number.",
        "A copy of your identification document is required to confirm your personal details in our verification system.",
        "Submit your passport or national identity card together with proof of your current address for identity confirmation.",
        "We need additional personal information and identification documents to finalize your identity verification.",
        "Your identity record cannot be completed until you provide your government-issued ID and personal details.",
        "Please share your identification number, date of birth, and a scanned copy of your official identity document."
    ],
    "PAYMENT_CARD_FRAUD" : [
        "Your credit card was charged for a purchase you did not make. Contact us immediately to dispute the transaction.",
        "We detected an unauthorized transaction on your debit card and require you to confirm whether you recognize the charge.",
        "A suspicious card payment of $489.99 was processed on your account. Report the transaction if it was not authorized.",
        "Your card has been used for an international purchase that appears unusual based on your recent spending activity.",
        "An unfamiliar merchant has charged your credit card. Review the transaction and submit a fraud dispute.",
        "Your debit card was charged twice for the same purchase. Contact the card issuer to request a reversal.",
        "We noticed a potentially fraudulent cash withdrawal using your card at an unfamiliar ATM location.",
        "A card payment was completed using your account, but our records indicate the transaction may not have been authorized by you.",
        "Your credit card has been charged a recurring amount that you do not recognize. Review the merchant and dispute the charge.",
        "An unusually large purchase was made with your payment card. Verify the transaction before additional charges occur.",
        "Your card was used to purchase goods from a merchant you have never visited. Please report the unauthorized payment.",
        "A suspicious online card transaction has been detected on your account involving an unknown retailer.",
        "Multiple small charges have appeared on your card, which may indicate unauthorized testing of the card.",
        "Your payment card was used at a location outside your usual region. Review the transaction for possible fraud.",
        "An unauthorized contactless payment was made using your card. Check your recent transaction history immediately.",
        "We identified a card purchase that does not match your typical spending pattern and may be fraudulent.",
        "Your credit card statement contains a charge from an unfamiliar business. Initiate a charge dispute if necessary.",
        "A payment was processed with your debit card while the physical card was reportedly in your possession.",
        "Your card has been used for several rapid transactions that may indicate fraudulent activity.",
        "An unknown merchant processed a payment against your card balance without your authorization.",
        "A fraudulent transaction was attempted using your card, and we need you to review the declined payment.",
        "Your card was charged for merchandise that you never ordered or received.",
        "An unfamiliar foreign currency transaction has appeared on your credit card statement.",
        "Your payment card was used for an online purchase that you did not authorize.",
        "We detected a suspicious card charge shortly after your card details may have been compromised.",
        "A transaction was completed using your card number without your knowledge or permission.",
        "Your debit card balance has been reduced by an ATM withdrawal you did not make.",
        "Several unauthorized purchases have been made using your credit card within a short period.",
        "A merchant has submitted a card charge for an amount higher than the purchase you authorized.",
        "Your card was charged after a transaction you cancelled, and the payment needs to be disputed.",
        "An unknown subscription charge was billed directly to your payment card without your authorization.",
        "A suspicious card transaction was processed while you were not present at the merchant location.",
        "Your card was used to make a purchase in another country despite you not traveling there.",
        "An unrecognized payment authorization is pending on your card and may represent attempted fraud.",
        "Your card has been used by an unknown party to make purchases without your consent."
    ],
    "BUSINESS_EMAIL_COMPROMISE" : [
        "CEO requests an urgent confidential wire transfer to a business partner.",
        "Executive instructs finance staff to immediately send funds to a specified bank account.",
        "Company director asks an employee to purchase gift cards for a confidential business matter.",
        "Senior executive requests gift card codes and asks the employee to send the codes by email.",
        "CEO impersonator asks an employee to handle an urgent payment while traveling.",
        "Finance director requests an immediate transfer for a confidential acquisition.",
        "Executive asks an employee to bypass normal approval procedures for an urgent transaction.",
        "Company president instructs payroll staff to urgently change an employee salary payment details.",
        "HR employee receives a message appearing to be from an executive requesting employee payroll records.",
        "Executive impersonator asks an assistant to secretly process a financial transaction.",
        "CEO requests immediate payment to support a confidential corporate project.",
        "Senior manager asks an employee to transfer company funds before an urgent deadline.",
        "Executive requests an employee to purchase prepaid cards for a business-related surprise.",
        "Company owner instructs accounting to process an unusual payment without informing colleagues.",
        "Managing director sends an urgent request to initiate a confidential bank transfer.",
        "Executive impersonator asks a junior employee to urgently contact them outside normal communication channels.",
        "CEO requests assistance completing a sensitive financial task while attending meetings.",
        "Senior executive instructs an employee to send company funds to an unfamiliar recipient.",
        "Business leader asks an employee to keep an urgent financial request strictly confidential.",
        "Executive requests immediate action because they are unavailable to complete the transaction personally.",
        "Company executive asks an assistant to coordinate an urgent payment with an external party.",
        "Director impersonator pressures an employee to process a transaction before consulting anyone.",
        "CEO asks an employee to urgently acquire gift cards for an important corporate purpose.",
        "Executive requests a confidential favor involving company money or financial resources.",
        "Senior manager instructs accounting staff to prioritize an unusual payment request.",
        "Company executive asks an employee to use personal funds temporarily for an urgent business matter.",
        "Executive impersonator claims to be in a meeting and demands immediate action by email.",
        "CEO requests a secret transaction related to a sensitive company negotiation.",
        "Senior executive asks an employee to urgently arrange payment for a confidential matter.",
        "Business owner instructs staff to complete a financial task without following standard verification procedures.",
        "Executive impersonator creates urgency around a confidential corporate payment request.",
        "Company leader asks an employee to discreetly handle an urgent financial obligation.",
        "Senior executive requests an employee to send digital gift vouchers for a business purpose.",
        "CEO impersonator pressures staff to act quickly without independently verifying the request.",
        "Executive requests a confidential transfer and insists that normal internal communication should be avoided."
    ],
    "INVESTMENT_SCAM": [
        "guaranteed high returns with little or no investment risk",
        "exclusive investment opportunity promising unusually large profits",
        "double your money quickly through a secret investment program",
        "limited-time opportunity to invest before guaranteed returns expire",
        "risk-free investment scheme offering fixed monthly profits",
        "early access to a private investment fund with exceptional returns",
        "investment opportunity claiming guaranteed daily trading profits",
        "join our exclusive wealth-building program and earn passive income",
        "secure high-yield returns through our professionally managed investment platform",
        "special insider investment opportunity available only to selected investors",
        "invest now to receive guaranteed profits from a rapidly growing venture",
        "high-return investment package requiring an immediate deposit",
        "exclusive pre-launch investment promising substantial future gains",
        "professional traders will invest your money and guarantee consistent profits",
        "private investment group offering returns far above normal market rates",
        "turn a small investment into significant profits within a short period",
        "investment advisor offering guaranteed returns regardless of market conditions",
        "urgent opportunity to participate in a highly profitable investment project",
        "automated investment system claiming to generate guaranteed passive income",
        "wealth management program promising unusually high annual returns",
        "exclusive opportunity to invest in a company before its value increases dramatically",
        "deposit funds into our investment account to begin earning guaranteed profits",
        "premium investment membership providing access to secret high-profit opportunities",
        "investment scheme promising fixed returns with zero possibility of loss",
        "financial opportunity claiming rapid wealth generation through managed investments",
        "selected investors invited to participate in a guaranteed profit-sharing program",
        "special investment package offering returns significantly above market averages",
        "private portfolio manager promising consistent profits from your deposited funds",
        "act immediately to secure your position in this high-return investment opportunity",
        "investment program claiming that your capital will generate guaranteed income automatically"
    ],
    "LOAN_CREDIT_SCAM": [
        "You are pre-approved for a low-interest personal loan; pay the processing fee today to release the funds.",
        "Your loan application has been approved, but you must pay an upfront insurance charge before disbursement.",
        "Get an instant business loan with no credit check after submitting a small registration payment.",
        "Congratulations, your requested loan amount is ready; send the activation fee to receive it.",
        "Your mortgage relief loan has been approved and requires an advance service charge.",
        "We can improve your credit score instantly after you pay our credit repair enrollment fee.",
        "A guaranteed loan is available regardless of your credit history; complete the advance payment first.",
        "Your emergency loan is approved, but a refundable security deposit is required before transfer.",
        "Pay the verification charge now to unlock your approved line of credit.",
        "You qualify for a government-backed loan, but an administrative fee must be paid immediately.",
        "Your loan funds are on hold because the required processing fee has not been received.",
        "We can consolidate all your debts into one low monthly payment after you pay the enrollment fee.",
        "Receive a high-value loan without collateral by paying a one-time documentation charge.",
        "Your credit card limit increase has been approved; pay the upgrade fee to activate it.",
        "A lender has selected you for guaranteed financing and needs an advance commission before release.",
        "Your student loan forgiveness application can be processed after payment of our handling fee.",
        "You have been approved for a quick cash loan; deposit the required advance amount to continue.",
        "We can remove your bad credit history and secure a new loan for a small upfront payment.",
        "Your loan agreement is ready for signing, but a mandatory clearance fee must be transferred first.",
        "You are eligible for a special zero-interest loan offer that requires a membership payment before approval.",
        "The bank requires a temporary collateral deposit before releasing your approved loan amount.",
        "Pay our broker fee now and we will guarantee approval for the loan you requested.",
        "Your credit relief program enrollment is pending until you submit the required service payment.",
        "An exclusive instant loan offer is available to you, but you must cover the fund transfer charges first.",
        "Your approved credit facility will expire today unless you pay the required activation and processing fees."
    ],
    "LOTTERY_PRIZE_SCAM": [
        "Congratulations! Your ticket has won the grand lottery prize.",
        "You have been selected as the winner of a cash prize in our international lottery.",
        "Claim your lottery winnings before the prize notification expires.",
        "Your email address was randomly chosen to receive a jackpot award.",
        "You are one of the lucky winners of this month's sweepstakes prize.",
        "Congratulations, you have won a million-dollar lottery prize.",
        "Your winning lottery number has been selected in our promotional draw.",
        "You have an unclaimed jackpot waiting for you.",
        "Claim your cash prize by confirming your winner information.",
        "You have been awarded a prize in the annual international lottery draw.",
        "Our records show that you are the selected winner of the grand prize.",
        "A winning prize notification has been issued in your name.",
        "You have won a substantial cash reward through a lucky draw.",
        "Your lottery prize is ready for collection.",
        "Congratulations! You are eligible to receive your sweepstakes winnings.",
        "You were randomly selected as the winner of our promotional prize draw.",
        "Your jackpot winnings remain unclaimed and require immediate attention.",
        "This is an official notification confirming your lottery prize award.",
        "You have won a cash prize in a contest you were automatically entered into.",
        "Your winning prize certificate has been approved for release."
    ],
    "REFUND_SCAM": [
        "You are eligible for a refund from your recent purchase; submit your claim to receive the money.",
        "We owe you a refund, but you must verify your details before the payment can be released.",
        "A duplicate charge was detected and a refund is waiting for your confirmation.",
        "Your overpayment has been approved for reimbursement; complete the refund request today.",
        "Claim your pending refund before the processing window expires.",
        "Our records show that you were charged too much and are entitled to money back.",
        "A refund has been initiated, but additional information is required to complete the transfer.",
        "You have an unclaimed reimbursement from a previous transaction.",
        "Your cancelled order qualifies for a full refund; confirm the payout details to receive it.",
        "We detected an excess payment and need you to complete a refund verification process.",
        "Your refund request is ready for settlement, pending confirmation of your account information.",
        "A merchant has issued money back to you, but the refund must be claimed through this process.",
        "You are entitled to compensation for an incorrect charge; submit the required information to collect it.",
        "Your reimbursement is on hold until you confirm your eligibility for the refund.",
        "A refund payment has been approved but cannot be deposited until verification is completed.",
        "We are returning funds from an accidental billing error; act now to avoid cancellation of the refund.",
        "Your unused balance is eligible for reimbursement and can be claimed immediately.",
        "An overcharge from a previous transaction has resulted in a pending refund for you.",
        "Your money-back claim has been selected for expedited processing after account confirmation.",
        "We need you to complete the final step before releasing your approved refund amount.",
        "A billing correction has created a refund credit that must be claimed before it expires.",
        "Your reimbursement has not been delivered because your refund details require confirmation.",
        "You qualify for a refund settlement due to a processing error in a previous payment.",
        "Claim the funds owed to you from a reversed transaction by completing the refund procedure.",
        "Our finance department has authorized a refund in your name and requires confirmation before disbursement."
    ],
    "INVOICE_PAYMENT_DIVERSION_SCAM": [
        "Please note that our bank account details have changed. Kindly send payment for invoice #INV-4821 to the new account listed below.",
        "Due to an internal banking update, all outstanding invoices must now be paid to our revised beneficiary account.",
        "Ignore the payment instructions on the original invoice and use these updated bank details for the transfer.",
        "Our accounts department has changed banks. Please redirect the pending invoice payment to the new account immediately.",
        "There was an error in the banking information previously provided. Please use the corrected account details for invoice settlement.",
        "Kindly update your vendor payment records with our new bank account before processing the attached invoice.",
        "The beneficiary account for this invoice has been changed. Please confirm once payment has been sent to the updated account.",
        "For security reasons, our previous company account is no longer accepting payments. Use the replacement account details below.",
        "Please hold payment on the original invoice until you receive the revised banking instructions attached.",
        "Our finance team has migrated to a new payment account. All future invoice transfers should be sent there.",
        "The payment instructions on invoice #10492 are outdated. Please remit the amount to the corrected beneficiary account.",
        "We urgently need you to redirect the scheduled supplier payment to our new bank account.",
        "Please cancel the transfer to our old account and resend the invoice payment using the new banking coordinates.",
        "A recent audit requires us to update our remittance details. Kindly use the attached account information for payment.",
        "Our banking partner has changed, so please send the outstanding invoice amount to the account specified in this message.",
        "Please update the beneficiary details for our company and process the pending invoice against the new account.",
        "The attached revised invoice contains updated payment instructions. Please use those details instead of the previous version.",
        "We have changed our collection account for operational reasons. Kindly remit payment to the new beneficiary.",
        "Before processing this invoice, please replace our existing bank details in your accounting system with the information below.",
        "The original remittance account has been closed. All invoice payments must now be directed to the replacement account.",
        "Please treat these updated wire instructions as effective immediately for the outstanding balance.",
        "Our finance department requests that you redirect this month's invoice payment to the newly designated account.",
        "There has been a change in our payment settlement account. Please use the revised details for all open invoices.",
        "Kindly do not send funds to the account shown on previous invoices; our remittance instructions have been updated.",
        "The vendor payment details in your system are no longer valid. Please update them before releasing the invoice payment.",
        "Please process the attached invoice using the alternative bank account provided in the remittance section.",
        "We are consolidating our accounts, and future invoice payments should be transferred to the new beneficiary account.",
        "Our accounts receivable team has issued revised payment instructions for the outstanding invoice balance.",
        "Please amend the scheduled payment destination before the transfer is executed and use our updated banking details.",
        "The invoice remains valid, but the bank account for receiving payment has changed. Please use the new details below.",
        "Due to a banking transition, please redirect all pending remittances associated with our invoices to the replacement account.",
        "We request an immediate update to our supplier profile so this invoice can be paid to the correct bank account.",
        "The attached notice contains new wire instructions for settling your outstanding invoice with us.",
        "Please disregard our previous remittance details and transfer the invoice amount according to the updated payment instructions.",
        "To avoid payment delays, kindly send the outstanding invoice funds to our newly specified beneficiary account."
    ],
    "DELIVERY_SCAM": [
        "Your parcel could not be delivered because the shipping address is incomplete. Update your delivery details to reschedule.",
        "A package addressed to you is being held at the distribution center. Pay the required redelivery fee to receive it.",
        "We attempted to deliver your shipment today, but no one was available. Choose a new delivery time now.",
        "Your package is awaiting customs clearance. Submit the required processing payment to avoid the shipment being returned.",
        "Delivery of your parcel has been suspended due to an incorrect postal code. Confirm the correct postcode immediately.",
        "Your shipment cannot proceed because the recipient address needs verification. Update your address details before the deadline.",
        "We were unable to complete delivery of your package. Pay a small rescheduling charge to arrange another attempt.",
        "Your parcel has arrived at the local depot but requires confirmation of the delivery location before dispatch.",
        "A delivery attempt failed because additional address information is missing. Provide the requested details to release the parcel.",
        "Your package will be returned to the sender unless you schedule a redelivery within the next 24 hours.",
        "Your shipment is temporarily held because the delivery address could not be validated. Correct the address to continue delivery.",
        "An outstanding delivery handling charge is required before your package can leave the sorting facility.",
        "Your parcel is waiting for collection instructions because the courier could not access the delivery location.",
        "We detected an issue with the delivery information for your shipment. Review and correct the details to prevent cancellation.",
        "Your package is at risk of being returned because the delivery window has expired. Select a new delivery option immediately.",
        "The courier requires an additional location confirmation before attempting delivery again. Submit the requested information.",
        "Your shipment has been placed on hold pending payment of a customs or import handling fee.",
        "We could not deliver your parcel because the house number appears to be missing. Update the address for another delivery attempt.",
        "Your package is scheduled for return unless you confirm that you still want the shipment delivered.",
        "A failed delivery attempt has been recorded for your parcel. Pay the service charge to arrange priority redelivery.",
        "Your shipment requires recipient confirmation before it can be transferred to the final delivery vehicle.",
        "The delivery driver was unable to locate your address. Update your location details to avoid losing the package.",
        "Your parcel is being held at a nearby facility because delivery instructions were not accepted. Submit new instructions now.",
        "A final delivery notice has been issued for your shipment. Confirm the delivery address before the package is returned.",
        "Your package cannot be released for delivery until the outstanding shipping adjustment fee is settled."
    ],
    "SUBSCRIPTION_SCAM": [
        "Your subscription will automatically renew today unless you cancel immediately.",
        "We detected an upcoming charge for your membership; click here to stop the renewal.",
        "Your free trial has ended and your account will be billed unless you cancel now.",
        "Cancel your unwanted subscription before the automatic payment is processed.",
        "Your membership renewal payment is scheduled; review or cancel your plan immediately.",
        "You have been enrolled in a premium subscription that requires immediate cancellation.",
        "Your subscription cancellation request failed; verify your details to avoid being charged.",
        "An annual membership fee will be deducted soon unless you terminate your subscription.",
        "Your streaming service subscription is set to renew at a higher price; cancel here.",
        "You are about to be charged for a subscription you may not recognize; manage it now.",
        "Your premium membership trial expires today and automatic billing will begin shortly.",
        "We could not process your subscription cancellation; take action before the next billing cycle.",
        "A recurring subscription payment has been scheduled on your account; cancel immediately.",
        "Your account has been selected for automatic enrollment in a paid membership plan.",
        "Your subscription price is increasing next month; confirm cancellation to avoid renewal.",
        "An unauthorized subscription renewal is pending; click below to stop the recurring charge.",
        "Your membership will renew automatically unless you confirm cancellation before midnight.",
        "You have an active subscription that will generate a recurring charge within 24 hours.",
        "Your trial membership converts to a paid plan today; cancel now to prevent billing.",
        "A subscription payment authorization has been created for your account; review it immediately.",
        "Your premium service membership is scheduled for renewal; cancel before the billing deadline.",
        "We noticed you have not used your subscription; cancel now to avoid the upcoming charge.",
        "Your recurring membership payment is pending approval; manage your subscription immediately.",
        "Your subscription account will continue billing every month unless you cancel through this link.",
        "Final notice: cancel your membership now or the next subscription payment will be deducted."
    ],
    "TECH_SUPPORT_SCAM": [
        "Your computer has been infected with a critical virus. Contact technical support immediately.",
        "We detected suspicious activity and malware on your device. Call our support team now.",
        "Microsoft security alert: your PC is compromised. Contact certified support immediately.",
        "Your device has been locked due to a security threat. Call technical support to unlock it.",
        "Our technicians detected multiple viruses on your computer and require immediate remote access.",
        "Your antivirus subscription has expired and your computer is now vulnerable. Contact support.",
        "A critical system error has been detected. Call our technical support department immediately.",
        "Your computer is sending malicious data to other systems. Contact support for urgent assistance.",
        "Security warning: your device may be compromised. Speak with a technician to resolve the issue.",
        "We detected unauthorized software on your computer. Contact our support specialists immediately.",
        "Your Windows system license has encountered an error. Call support to restore functionality.",
        "A dangerous virus has corrupted your operating system. Contact a technician for immediate repair.",
        "Your device is at risk of permanent damage due to a system failure. Call technical support now.",
        "Our security center detected malware attempting to steal data from your computer. Contact support.",
        "Your computer requires urgent security maintenance. Call our certified technicians immediately.",
        "A remote diagnostic scan found critical errors on your system. Contact technical support to fix them.",
        "Your firewall has been disabled and your computer is exposed to threats. Call support immediately.",
        "We detected a serious problem with your computer hardware and software. Speak to a technician.",
        "Your system has been compromised by hackers. Contact our security support team for assistance.",
        "Critical alert: malicious software has been detected on your device. Call technical support now.",
        "Your computer needs immediate virus removal service. Contact our technical assistance department.",
        "An unauthorized program is controlling your device. Call support to secure your computer.",
        "Your system security has expired and dangerous threats were detected. Contact technical support.",
        "We detected unusual network activity from your computer. Speak with a technician immediately.",
        "Your device may stop functioning due to a critical operating system error. Call support now.",
        "A security scan found multiple threats that require professional technical assistance.",
        "Your computer has been flagged for suspicious activity. Contact our support team for immediate resolution.",
        "Warning: hackers may have gained access to your device. Call our technical experts immediately.",
        "Your operating system requires urgent repair to prevent data loss. Contact technical support.",
        "A critical security issue has been detected on your computer. Call our help desk for immediate assistance."
    ],
    "UTILITY_SERVICE_DISCONNECTION_SCAM": [
        "Your electricity service will be disconnected today unless the outstanding balance is paid immediately.",
        "Final notice: your water supply is scheduled for shutoff within 24 hours due to an unpaid utility bill.",
        "Urgent action required to prevent your gas service from being disconnected for nonpayment.",
        "Your power account has an overdue balance and service termination is pending unless payment is made today.",
        "We received a disconnection order for your utility account; settle the balance immediately to keep service active.",
        "Your electricity connection will be suspended tonight unless you resolve the billing issue immediately.",
        "Immediate payment is required to stop the scheduled shutoff of your water service.",
        "Your gas utility account is past due and disconnection technicians have been assigned to your address.",
        "Avoid an interruption in electric service by paying the outstanding utility balance before the deadline.",
        "Your household utility service has entered the final disconnection stage because payment has not been received.",
        "A service termination notice has been issued for your electricity account due to unresolved charges.",
        "Your water service will be disconnected unless the overdue account balance is cleared immediately.",
        "This is your final warning before gas service is suspended for an unpaid utility amount.",
        "Your electricity provider has scheduled service termination for today unless immediate action is taken.",
        "An unpaid balance has triggered a pending shutoff order on your utility account.",
        "Prevent immediate disconnection of your power supply by resolving the overdue payment now.",
        "Your utility service is at risk of termination and requires urgent payment to remain connected.",
        "Our records show your water account is delinquent and service shutoff will proceed without prompt payment.",
        "Your gas and energy service may be disconnected today because your account remains unpaid.",
        "Final utility alert: immediate payment is required to cancel the scheduled service disconnection."
    ],
    "MARKETPLACE_ECOMMERCE_SCAM": [
        "A buyer on an online marketplace asks the seller to ship an item after sending a fake payment confirmation.",
        "A seller advertises a popular product at an unusually low price, collects payment, and never sends the item.",
        "A marketplace buyer claims payment is being held and asks the seller to pay a release fee.",
        "A fraudulent seller creates a fake product listing using stolen photos and accepts orders for goods they do not possess.",
        "A buyer sends a counterfeit payment receipt to convince a seller that funds have been transferred.",
        "A scammer impersonates a legitimate marketplace support team and claims a seller must pay a verification fee to continue selling.",
        "A fake online store advertises heavily discounted branded merchandise but never delivers the purchased products.",
        "A marketplace seller requests payment outside the platform to avoid supposed transaction fees and then disappears.",
        "A buyer pressures a seller to communicate through an external messaging app and sends a fraudulent purchase arrangement.",
        "A scammer lists a non-existent rental, vehicle, collectible, or electronic product and requests an advance deposit.",
        "A fraudulent merchant advertises products that are significantly different from what is shown in the listing.",
        "A fake buyer claims to have accidentally overpaid and asks the seller to return the difference before the original payment fails.",
        "A marketplace scammer creates urgency by claiming multiple buyers are interested and demands immediate payment for an item.",
        "A fraudulent seller uses copied reviews and images to make a fake online storefront appear legitimate.",
        "A buyer claims that an additional insurance payment is required before marketplace funds can be released to the seller.",
        "A scammer advertises scarce or high-demand products such as concert merchandise or gaming consoles that they never intend to provide.",
        "A fraudulent online merchant accepts orders during a flash sale and disappears after collecting payments from customers.",
        "A seller asks a customer to pay a separate customs or handling charge that was not disclosed in the original listing.",
        "A marketplace scammer impersonates a trusted individual seller by copying their profile, listings, and product descriptions.",
        "A fraudulent buyer arranges for a courier to collect an item and sends the seller a fake message claiming payment is pending.",
        "A scammer advertises counterfeit products as genuine goods and uses deceptive descriptions to justify premium prices.",
        "A fake marketplace listing offers an expensive item at a dramatic discount and requires an immediate reservation deposit.",
        "A fraudulent seller repeatedly postpones shipment while inventing excuses after receiving payment for an online purchase.",
        "A scammer creates a temporary online shop around a trending product and closes it after collecting customer payments.",
        "A buyer claims a marketplace transaction requires the seller to purchase a special shipping label from an external website.",
        "A fraudulent merchant offers bulk discounts for products that do not actually exist in inventory.",
        "A scammer poses as an authorized reseller and sells fake event tickets, luxury goods, or electronics through an online marketplace.",
        "A marketplace seller requests a non-refundable booking fee to reserve an item and then removes the listing.",
        "A fake merchant uses misleading product availability notices to collect pre-orders for goods that will never be supplied.",
        "A scammer contacts users who interacted with a legitimate listing and offers the same item through an unauthorized duplicate sale."
    ],
    "TAX_SCAM": [
        "Tax authority claims you owe overdue taxes and demands immediate payment to avoid penalties",
        "Message threatens arrest or legal action unless an alleged tax debt is paid immediately",
        "Fake tax department notice says your tax return contains discrepancies requiring urgent action",
        "Scammer claims unpaid income tax will result in seizure of assets unless payment is made",
        "Email impersonates a tax authority and demands settlement of an outstanding tax liability",
        "Notice claims your tax filing was rejected and demands payment of a processing penalty",
        "Tax agency impersonator threatens wage garnishment over an alleged unpaid tax balance",
        "Message claims a tax audit has found undeclared income and demands immediate settlement",
        "Fake government tax notice says enforcement proceedings will begin unless taxes are paid",
        "Scammer claims a property tax bill is overdue and threatens legal consequences for nonpayment",
        "Message alleges unpaid business taxes and demands urgent resolution to avoid sanctions",
        "Fake tax authority claims a tax compliance violation requires immediate payment of a fine",
        "Notice says a previous tax payment was insufficient and demands the remaining balance",
        "Scammer impersonates a revenue department and threatens prosecution for alleged tax evasion",
        "Message claims an outstanding tax assessment has become final and requires immediate payment",
        "Fake tax notice demands payment to prevent suspension of a tax identification status",
        "Email claims inheritance or estate taxes must be paid immediately to avoid government penalties",
        "Scammer alleges capital gains taxes are overdue and demands urgent settlement",
        "Message claims customs or import taxes remain unpaid and threatens government enforcement",
        "Fake revenue authority notice says late tax filing penalties must be paid immediately",
        "Scammer claims a tax lien will be placed on your property unless an alleged debt is settled",
        "Message impersonates a tax office and claims enforcement officers will visit over unpaid taxes",
        "Fake tax demand alleges underreported earnings and requires immediate payment of additional tax",
        "Notice claims a tax investigation has identified unpaid liabilities requiring urgent resolution",
        "Scammer threatens criminal tax charges unless an alleged outstanding tax obligation is paid"
    ],
    "IMMIGRATION_VISA_SCAM": [
        "Your visa application has been approved. Pay the required processing fee immediately to receive your travel authorization.",
        "We are contacting you regarding an urgent immigration matter that requires immediate action to avoid cancellation of your visa.",
        "Congratulations, you have been selected for permanent residency through a special immigration program. Submit the processing payment now.",
        "Your immigration application is incomplete and will be rejected unless you pay the document verification fee today.",
        "A government immigration officer has reviewed your case and requires an immediate payment to continue processing your residency application.",
        "Your visa has been placed on hold because an additional immigration clearance fee is required before approval.",
        "You qualify for expedited permanent residency. Send the required processing payment to secure your eligibility before the deadline.",
        "Your work visa petition requires urgent action. Pay the immigration filing charge immediately to prevent cancellation.",
        "We detected an issue with your immigration status. Contact our representative immediately and pay the required legal processing fee.",
        "Your green card renewal has been approved pending payment of a mandatory immigration administration charge.",
        "You have been granted eligibility for a special visa program, but your application will expire unless the registration fee is paid immediately.",
        "Immigration authorities require you to pay a penalty for an alleged violation before your residency status can be restored.",
        "Your citizenship application has been selected for fast-track processing. Complete the required payment to reserve your appointment.",
        "A final immigration decision has been issued, but you must pay a release fee before receiving your official visa documents.",
        "Your dependent visa application requires an urgent supplemental payment before family sponsorship can proceed.",
        "We can guarantee approval of your immigration application through our exclusive government processing channel for an immediate service fee.",
        "Your residency permit is about to expire, and immediate payment is required to prevent removal from the country.",
        "You have been randomly selected for a government visa lottery opportunity and must pay the enrollment fee to claim your immigration eligibility.",
        "An immigration enforcement case has been opened under your name. Pay the settlement amount immediately to avoid deportation proceedings.",
        "Your visa interview appointment has been reserved, but confirmation requires payment of an urgent immigration processing charge."
    ],
    "JOB_RECRUITMENT_SCAM": [
    "You have been selected for a high-paying remote position despite not submitting an application.",
    "Our recruitment team found your profile and wants to hire you immediately with no interview required.",
    "Congratulations, you are hired. Complete the onboarding steps today to secure your position.",
    "A recruiter is offering guaranteed employment if you act quickly before the vacancy closes.",
    "You have been shortlisted for a job and must contact the hiring manager through a messaging app.",
    "We are expanding our workforce and offering flexible work-from-home jobs with unusually high daily earnings.",
    "Your resume has been approved for an international job opportunity with immediate placement.",
    "A company representative claims you were randomly selected for a paid employment opportunity.",
    "We have reviewed your profile and would like to offer you a position without a formal application process.",
    "An employer promises substantial income for simple online tasks with immediate job confirmation.",
    "You are invited to join a recruitment program that guarantees placement with a major company.",
    "A hiring agent claims there are limited positions remaining and pressures you to accept immediately.",
    "You have been pre-approved for a remote role and only need to complete the joining formalities.",
    "A recruiter contacts you unexpectedly with an exclusive employment opportunity matching your profile.",
    "Your job application has supposedly progressed even though you do not remember applying for the position.",
    "A company offers immediate employment and asks you to communicate only through unofficial channels.",
    "You are promised a lucrative part-time role that requires no experience and can start today.",
    "A recruitment agency claims it can guarantee you a job with a well-known employer.",
    "An unsolicited message offers a job with exceptional salary and benefits for minimal qualifications.",
    "You have been selected for a confidential employment opportunity and must respond within hours.",
    "A recruiter claims your skills are urgently needed for a position and skips the normal hiring process.",
    "An employer offers instant placement in a job and emphasizes that the opportunity will disappear soon.",
    "You receive an unexpected invitation to join a company as a remote employee with unusually easy requirements.",
    "A supposed hiring manager claims you passed all selection stages without attending an interview.",
    "A job offer promises guaranteed employment, rapid onboarding, and unusually high compensation for simple work."
],
    "ROMANCE_RELATIONSHIP_SCAM": [
        "I know we have never met in person, but I feel a deep connection with you and need your help during an emergency.",
        "My love, I am stranded overseas and need money for a flight so we can finally be together.",
        "I cannot access my bank account while deployed, so please send funds to help me until I return home.",
        "I want to visit you, but customs is holding my package and I need you to pay the release fee.",
        "You are the only person I trust enough to help me with this temporary financial problem.",
        "I have fallen in love with you online and need financial assistance to overcome a crisis before we can meet.",
        "My passport and belongings were stolen while traveling, and I desperately need money to get home.",
        "I bought a ticket to come see you, but an unexpected emergency fee is preventing me from traveling.",
        "Please keep our relationship private for now and send the money directly because I am embarrassed about my situation.",
        "I inherited a large amount of money but cannot access it until I pay legal and processing expenses.",
        "I need help paying for medical treatment after an accident, and I have nobody else I can turn to.",
        "Once this financial problem is resolved, I promise we can finally start our life together.",
        "The military rules prevent me from accessing my funds, so I need my partner to help cover an urgent expense.",
        "I sent you a valuable gift, but the courier says you must pay a fee before it can be delivered.",
        "Our future together depends on solving this problem quickly, and I need you to send money today.",
        "I am planning our wedding, but I need temporary financial help before I can travel to meet you.",
        "Please do not tell your family or friends about this request because they may misunderstand our relationship.",
        "I need you to prove that you truly love and trust me by helping me financially during this difficult time.",
        "After months of building our relationship online, I need emergency funds before we can finally meet in person.",
        "I love you deeply, but I am facing an unexpected crisis and need money from you immediately to resolve it."
    ],
    "EXTORTION_BLACKMAIL": [
        "Pay the demanded amount immediately or damaging information about you will be released publicly.",
        "We have compromising material involving you and will share it with your contacts unless you pay.",
        "Send payment within the deadline or we will expose private photos and messages.",
        "Your personal data has been obtained and will be published unless you meet our financial demands.",
        "We recorded sensitive activity from your device and will distribute the footage if you refuse to pay.",
        "A payment is required to prevent embarrassing information from being sent to your family and colleagues.",
        "We have access to confidential material connected to you and will make it public unless compensated.",
        "Transfer the requested money now or face public exposure of damaging personal information.",
        "Your private files are in our possession, and payment is the only way to stop their release.",
        "We will contact everyone in your address book with compromising content unless our demand is met.",
        "You have been targeted for exposure, and failure to pay will result in serious reputational consequences.",
        "We possess evidence that could damage your reputation and require payment to keep it confidential.",
        "Meet our monetary demand before the deadline or sensitive information about you will be disclosed.",
        "We are prepared to release embarrassing material publicly unless you provide the requested payment.",
        "Your secrets will remain private only if you comply with our financial demands immediately.",
        "Failure to send the demanded amount will result in private information being shared online.",
        "We have collected compromising evidence and will expose you unless you pay for its suppression.",
        "Pay us to prevent the distribution of sensitive content connected to your personal life.",
        "You have limited time to meet our demand before damaging material is sent to people you know.",
        "This is your final warning: provide payment or we will publicly reveal the information we possess."
    ],
    "BENIGN": [
        "Thank you for your email. I will review the information and get back to you soon.",
        "Please find the meeting agenda attached for tomorrow's discussion.",
        "Your order has been successfully processed and is being prepared for shipment.",
        "We have received your request and our support team is reviewing it.",
        "Reminder: our weekly team meeting will take place at 10:00 AM on Monday.",
        "Thank you for subscribing to our company newsletter.",
        "Your appointment has been confirmed for the requested date and time.",
        "Please let us know if you have any questions about the attached document.",
        "The project update meeting has been moved to Thursday afternoon.",
        "We appreciate your continued support and look forward to working with you.",
        "Your password was successfully changed through the account settings page.",
        "A new version of our application is now available for download from our official website.",
        "Thank you for completing the customer satisfaction survey.",
        "Your support ticket has been updated with a response from our team.",
        "Please review the draft and share your feedback before the deadline.",
        "The requested report has been generated and is available in your dashboard.",
        "We are writing to confirm that your reservation has been successfully completed.",
        "Your monthly account statement is now available for viewing.",
        "The maintenance work on our systems has been completed successfully.",
        "Thank you for attending our webinar. We hope you found it useful.",
        "Please save the date for our upcoming company event next month.",
        "Your application has been received and is currently under review.",
        "The attached document contains the notes from our recent meeting.",
        "We have updated our privacy policy to provide additional clarification.",
        "Your package was delivered successfully according to the shipping carrier.",
        "Thank you for renewing your existing service for another year.",
        "The training session recording is now available for registered participants.",
        "Please contact our office during business hours if you need assistance.",
        "Your requested account information has been updated successfully.",
        "We are pleased to announce the launch of our new product feature.",
        "The invoice has been received and recorded in our accounting system.",
        "Thank you for your purchase. Your receipt is included with this message.",
        "Our office will be closed on the upcoming public holiday.",
        "Please review your scheduled appointments in the customer portal.",
        "The conference registration deadline has been extended until next week.",
        "We have received your feedback and shared it with the relevant team.",
        "Your document has been uploaded successfully to the shared workspace.",
        "Thank you for participating in our community discussion.",
        "The latest company newsletter is attached for your convenience.",
        "Please join us for the scheduled presentation using the meeting details provided.",
        "Your membership remains active and will continue according to your selected plan.",
        "We have completed the requested changes to your service preferences.",
        "The requested information is included in the attached file.",
        "Thank you for confirming your attendance at the upcoming event.",
        "Our records indicate that your contact information was recently updated.",
        "The software update includes general performance improvements and bug fixes.",
        "Please review the project timeline before our next planning session.",
        "Your registration for the online course has been successfully confirmed.",
        "We appreciate your interest in learning more about our services.",
        "The meeting notes have been shared with all attendees.",
        "Your request for additional information has been forwarded to the appropriate department.",
        "Thank you for contacting customer support. We will respond during normal business hours.",
        "The event schedule has been updated with the latest session information.",
        "Please see the attached presentation from today's discussion.",
        "Your profile settings have been saved successfully.",
        "We are conducting scheduled maintenance this weekend to improve system performance.",
        "Thank you for registering for our upcoming workshop.",
        "The requested cancellation has been processed successfully.",
        "Please update your calendar with the revised meeting date.",
        "Your feedback helps us improve our products and services.",
        "We have added your request to our internal support queue.",
        "The annual report is now available for interested stakeholders.",
        "Thank you for being a valued member of our community.",
        "Please review the attached contract and send any non-urgent questions to our team.",
        "The service interruption has been resolved and normal operations have resumed.",
        "Your confirmation email is included for your records.",
        "We look forward to seeing you at the scheduled meeting.",
        "The new office hours will begin starting next Monday.",
        "Thank you for your patience while we completed the requested review.",
        "This is a friendly reminder about the upcoming deadline for submitting your documents."
    ]
}

URGENCY_PATTERNS_REGEX = [

    # direct urgency
    r"\burgent\b",
    r"\burgently\b",
    r"\bimmediately\b",
    r"\basap\b",
    r"\bright\s+away\b",
    r"\bat\s+once\b",
    r"\bwithout\s+delay\b",
    r"\bact\s+now\b",
    r"\bdo\s+not\s+delay\b",
    r"\bpromptly\b",

    # explicit short deadlines
    r"\bwithin\s+\d+\s*(?:minutes?|hours?|days?)\b",
    r"\bwithin\s+(?:one|an?)\s*(?:minute|hour|day)\b",
    r"\b(?:in|within)\s+the\s+next\s+\d+\s*(?:minutes?|hours?|days?)\b",

    # temporal deadlines
    r"\bbefore\s+(?:the\s+)?(?:end\s+of\s+the\s+day|deadline)\b",
    r"\bby\s+(?:the\s+)?end\s+of\s+(?:today|the\s+day)\b",
    r"\btoday\b",
    r"\bthis\s+(?:morning|afternoon|evening)\b",
    r"\bby\s+\d{1,2}(?::\d{2})?\s*(?:am|pm)?\b",
    r"\bby\s+(?:today|tomorrow|tonight)\b",

    # explicit expiration / cutoff language
    r"\bbefore\s+(?:it\s+)?expires?\b",
    r"\bexpires?\s+(?:today|tomorrow|soon|within)\b",
    r"\bdeadline\b",
    r"\b(?:final|last)\s+(?:notice|warning|reminder)\b",
]


URGENCY_FACTOR_SEMANTICS = {

    "IMMEDIATE_ACTION": [
        "Verify your account immediately.",
        "Take action immediately.",
        "Act now.",
        "Respond immediately.",
        "Complete the required action right away.",
        "Immediate action is required.",
        "Do not delay this action.",
        "You must act immediately.",
        "Please act without delay.",
        "Complete this request as soon as possible.",
    ],

    "EXPLICIT_DEADLINE": [
        "Complete the verification within 24 hours.",
        "You must respond within the next 24 hours.",
        "You have 48 hours to take action.",
        "Respond before the deadline.",
        "Complete this request by tomorrow.",
        "You must act before the specified deadline.",
        "Your response is required within a limited time.",
        "Complete the required action before the stated time expires.",
        "You must respond by the specified date.",
        "Take action before the deadline passes.",
        "within the next few hours",
        "within the next 24 hours",
        "within 24 hours",
        "within 48 hours",
        "you have 24 hours to respond",
        "you have a limited amount of time to act",
        "complete this within the required time period",
        "act before your time runs out",
    ],

    "DELAY_CONSEQUENCE": [
        "Failure to act will result in a negative consequence.",
        "If you do not respond, your account may be restricted.",
        "Failure to complete the request may result in account suspension.",
        "Your access may be limited if you do not take action.",
        "Failure to respond could cause loss of access.",
        "Delaying this action may result in service restrictions.",
        "If you fail to act, your account may be suspended.",
        "Failure to complete the verification will have consequences.",
        "Not responding may result in restricted access.",
        "Failure to act before the deadline may result in account limitations.",
        "Failure to complete the required action will result in account suspension.",
        "Failure to verify your information will result in restricted account access.",
        "If you do not complete the verification, your account will be suspended.",
        "Failure to act within the required time will result in service restrictions.",
        "Not completing the requested action will result in temporary suspension.",
        "Failure to respond will result in restricted access.",
    ],

    "PERMANENT_LOSS": [
        "Failure to act may result in permanent loss of access.",
        "Your account may be permanently restricted.",
        "You may permanently lose access to your account.",
        "Failure to respond could result in permanent account suspension.",
        "Your access may be permanently removed.",
        "Take action to prevent permanent account restrictions.",
        "Your account may be permanently disabled.",
        "Failure to act could result in irreversible loss.",
        "You risk permanently losing access to your services.",
        "This action is required to prevent permanent loss.",
    ],

    "EXPLICIT_URGENCY_LANGUAGE": [
        "This matter requires urgent attention.",
        "Urgent action is required.",
        "This is an urgent matter.",
        "Immediate attention is required.",
        "Please treat this matter as urgent.",
        "This situation requires prompt action.",
        "Your immediate attention is required.",
        "This issue must be addressed urgently.",
        "An urgent response is necessary.",
        "This requires immediate attention.",
    ],

    "SCARCITY_TIME_PRESSURE": [
        "This opportunity will expire soon.",
        "This offer is available for a limited time.",
        "Act now before the opportunity expires.",
        "Limited time remains to take advantage of this offer.",
        "This is your last chance.",
        "The offer will not remain available for long.",
        "Only a limited time is available.",
        "The opportunity will expire shortly.",
        "Act quickly before this option disappears.",
        "This offer ends soon.",
    ],
}


DECAY_RATES = {
    "IMMEDIATE_ACTION": 0.92,
    "EXPLICIT_DEADLINE": 0.98,
    "DELAY_CONSEQUENCE": 0.95,
    "PERMANENT_LOSS": 0.97,
    "EXPLICIT_URGENCY_LANGUAGE": 0.90,
    "SCARCITY_TIME_PRESSURE": 0.93,
}


URGENCY_WEIGHTS = {
    "IMMEDIATE_ACTION": 0.22,
    "EXPLICIT_DEADLINE": 0.22,
    "DELAY_CONSEQUENCE": 0.18,
    "PERMANENT_LOSS": 0.18,
    "EXPLICIT_URGENCY_LANGUAGE": 0.12,
    "SCARCITY_TIME_PRESSURE": 0.08,
}


URGENCY_PATTERNS_SEMANTIC = [

    # Immediate action
    "The recipient is instructed to take action immediately.",
    "The recipient is asked to act right away.",
    "The message requires immediate action from the recipient.",
    "The recipient is told not to delay taking action.",
    "The sender expects the recipient to act without waiting.",
    "The message tells the recipient to respond as soon as possible.",
    "The recipient is urged to complete the requested action immediately.",
    "The sender strongly emphasizes acting now.",
    "The message indicates that action should be taken at once.",
    "The recipient is encouraged to handle the matter immediately.",

    # Pressure to act quickly
    "The recipient is pressured to act quickly.",
    "The message creates pressure for the recipient to act fast.",
    "The sender urges the recipient to act without delay.",
    "The recipient is pushed to make a decision quickly.",
    "The message attempts to rush the recipient into taking action.",
    "The recipient is encouraged to respond quickly rather than later.",
    "The sender emphasizes the need for a prompt response.",
    "The message places pressure on the recipient to act quickly.",
    "The recipient is expected to complete the requested action promptly.",
    "The message discourages the recipient from taking time to consider the request.",

    # Very little time
    "The message suggests that very little time remains to act.",
    "The recipient is given only a short period to respond.",
    "The message creates a sense of limited time to complete the action.",
    "The recipient is told that there is not much time left.",
    "The message suggests that the opportunity to act will disappear soon.",
    "The recipient is warned that the available time is running out.",
    "The message indicates that the recipient must act before time expires.",
    "The sender suggests that waiting even briefly could be a problem.",
    "The recipient is given a narrow window in which to take action.",
    "The message communicates that action cannot safely be postponed.",

    # Deadlines
    "The recipient is given a deadline for taking action.",
    "The recipient is told to complete the action before a specified time.",
    "The message requires action before a particular deadline.",
    "The recipient is instructed to respond by a stated date or time.",
    "The message indicates that the requested action must be completed within a fixed period.",
    "The recipient is told that the deadline is approaching.",
    "The message emphasizes that the deadline is near.",
    "The recipient is warned that missing the deadline may cause a problem.",
    "The sender stresses that the requested action must be completed before time runs out.",
    "The message establishes a time limit for responding.",

    # Expiration / soon-ending conditions
    "The recipient is told that an opportunity may expire soon.",
    "The message warns that access or availability may end shortly.",
    "The recipient is told that the current situation is temporary and requires prompt action.",
    "The message indicates that a requested action will only be available for a limited time.",
    "The recipient is warned that waiting may cause an option to expire.",
    "The message suggests that the recipient must act before an opportunity closes.",
    "The recipient is told that a temporary window for action is ending soon.",
    "The message communicates that a benefit or opportunity is time-limited.",
    "The recipient is urged to act before a temporary condition ends.",
    "The message implies that postponing action may cause the opportunity to disappear.",

    # Consequences of delay
    "The recipient is warned that delaying action may cause negative consequences.",
    "The message suggests that waiting could create a problem for the recipient.",
    "The recipient is told that failure to act quickly may lead to consequences.",
    "The message links delay with an undesirable outcome.",
    "The recipient is warned that postponing the action could make the situation worse.",
    "The message implies that consequences will occur if action is delayed.",
    "The recipient is pressured by the possibility of consequences for waiting.",
    "The sender emphasizes that delay could result in loss or inconvenience.",
    "The message suggests that immediate action is necessary to avoid a negative result.",
    "The recipient is warned that inaction may trigger an unwanted outcome.",

    # Escalation / final warning
    "The message presents the request as a final warning requiring prompt action.",
    "The recipient is told that this is the last chance to act.",
    "The sender describes the request as a final opportunity to respond.",
    "The recipient is warned that no further opportunity may be provided.",
    "The message suggests that the situation has reached a final stage.",
    "The recipient is told that failure to act now will cause the matter to escalate.",
    "The sender indicates that immediate attention is required before further action is taken.",
    "The message frames the request as the final step before consequences occur.",
    "The recipient is warned that the next stage will occur if they do not act promptly.",
    "The message communicates that urgent attention is required before escalation.",

    # General time-pressure / urgency
    "The message creates a strong sense of urgency.",
    "The message makes the recipient feel that immediate compliance is necessary.",
    "The sender uses time pressure to encourage rapid action.",
    "The message attempts to make the recipient prioritize the request immediately.",
    "The recipient is made to feel that postponing the action is unsafe or undesirable.",
    "The message encourages the recipient to act now rather than later.",
    "The sender emphasizes speed as an important part of completing the request.",
    "The message communicates that prompt action is critical.",
    "The recipient is strongly encouraged to avoid delaying the requested response.",
    "The message conveys that the requested action should happen as quickly as possible."
]


intent_risk = {

    # Credential and identity attacks
    "CREDENTIAL_PHISHING": 0.90,
    "ACCOUNT_TAKEOVER": 0.95,
    "IDENTITY_INFORMATION_THEFT": 0.95,

    # Financial fraud
    "PAYMENT_CARD_FRAUD": 0.90,
    "BUSINESS_EMAIL_COMPROMISE": 0.95,
    "INVOICE_PAYMENT_DIVERSION_SCAM": 0.95,
    "LOAN_CREDIT_SCAM": 0.75,
    "INVESTMENT_SCAM": 0.85,
    "CRYPTOCURRENCY_SCAM": 0.85,

    # Impersonation scams
    "GOVERNMENT_IMPERSONATION": 0.85,
    "TAX_SCAM": 0.90,
    "IMMIGRATION_VISA_SCAM": 0.85,
    "UTILITY_SERVICE_DISCONNECTION_SCAM": 0.80,

    # Delivery and service scams
    "DELIVERY_SCAM": 0.65,
    "SUBSCRIPTION_SCAM": 0.65,
    "TECH_SUPPORT_SCAM": 0.85,
    "REFUND_SCAM": 0.75,

    # Malware and direct compromise
    "MALWARE_DELIVERY": 0.95,

    # Recruitment and prize scams
    "JOB_RECRUITMENT_SCAM": 0.70,
    "LOTTERY_PRIZE_SCAM": 0.70,

    # Commerce scams
    "SHOPPING_ECOMMERCE_SCAM": 0.65,
    "FAKE_MARKETPLACE_P2P_SCAM": 0.75,

    # Social engineering scams
    "EXTORTION_BLACKMAIL": 0.95,
    "ROMANCE_RELATIONSHIP_SCAM": 0.70,
    "CHARITY_SCAM": 0.60,
}
